version: "3"  # optional since v1.27.0
services:
  app:
    image: 'restaurant-service:latest'
    build:
      context: .

    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
