server:
  port: 8000
spring:
  application:
    name: api-service
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      healthcheck:
        enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
resilience4j:
  retry:
    instances:
      numero-veces:
        max-attempsts: 10