server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:33067/otrs?useUnicode=true&characterEncodign=UTF-8&serverTImezone=UTC
    username: irving_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20