spring:
  application:
    name: security-service
server:
  port: 9001
  servlet:
    contextPath: /auth
security:
  user:
    password: password
  oauth2:
    resource:
      filter-order: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true