server:
  port: 8761
spring:
  application:
    name: eureka-server-irv
#Propiedades para que no haga el registro consigo mismo
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20