server:
  port: 8085
spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:33067/otrs?useUnicode=true&characterEncodign=UTF-8&serverTImezone=UTC
    username: irving_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#  server.port=8085
#  spring.application.name=restaurant-service
#  spring.jpa.show-sql=true
#  spring.datasource.url=jdbc:mysql://localhost:33067/otrs?useUnicode=true&characterEncodign=UTF-8&serverTImezone=UTC
#  spring.datasource.username=irving_user
#  spring.datasource.password=password
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.h2.console.enabled=true
#spring.data.jpa.repositories.bootstrap-mode=default